export enum ICalKey {
    Rrule = 'RRULE',
    Exdate = 'EXDATE',
    Created = 'CREATED',
    LastModified = 'LAST-MODIFIED',
    Dtstamp = 'DTSTAMP',
    Dtstart = 'DTSTART',
    Dtend = 'DTEND',
    Location = 'LOCATION',
    Status = 'STATUS',
    Summary = 'SUMMARY',
    Description = 'DESCRIPTION',
    Transp = 'TRANSP',
    Sequence = 'SEQUENCE',
    Organizer = 'ORGANIZER',
    Uid = 'UID',
    Attendee = 'ATTENDEE',
    Value = 'VALUE',
    Begin = 'BEGIN',
    End = 'END',
}